baseURL = "https://botoxx.github.io/"
languageCode = "en-us"
title = "Botond Geiszt | DevOps Engineer"
theme = "niello"

[params]
  author = "Botond Geiszt"
  description = "DevOps Engineer specializing in cloud-native solutions, CI/CD, and automation"
  favicon = "favicon.ico"
  
[params.info]
  job = "DevOps Engineer"
  phone = "+36203814568"
  email = "g.pont.botond@gmail.com"
  linkedin = "https://linkedin.com/in/botond-geiszt"

[params.profileImage]
  src = "profile.jpg"
  alt = "Profile Image"
